---
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job 1
        run: echo "at first you are awesome"

  job2:
    runs-on: ubuntu-latest
    needs: job1 
    steps:
      - name: job2
        run: echo "at last only you are awesome"
...
