---
name: Run Python Script
  workflow_dispatch:
on:
  # schedule:
  #   - cron: '45 7 * * *'


jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Python script
      run: python demo.py
...
